---
- include: java8.yml
  when: ansible_distribution == "Ubuntu"

- name: Install RPM package
  yum:
    name: "{{ rpm_get_url }}"
    state: present
  notify:
    - restart idh
  when: ansible_pkg_mgr == "yum"

- name: Install DEB package
  apt:
    deb: "{{ deb_get_url }}"
    state: present
    dpkg_options: "--force-overwrite"
  notify:
    - restart idh 
  when: ansible_pkg_mgr == "apt"

- name: Start and enable IDH service
  service:
    name: identity-harmonization
    state: started
    enabled: yes
